"""API models for Denis Unified V1 FastAPI server - OpenAI compatible."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """OpenAI compatible chat message."""
    role: str = Field(..., description="Role of the message author")
    content: str = Field(..., description="Content of the message")
    name: Optional[str] = Field(None, description="Optional name for the participant")


class ChatCompletionRequest(BaseModel):
    """OpenAI compatible chat completion request."""
    model: str = Field(..., description="Model to use for completion")
    messages: List[ChatMessage] = Field(..., description="List of messages comprising the conversation")
    max_tokens: Optional[int] = Field(None, description="Maximum number of tokens to generate")
    temperature: Optional[float] = Field(None, description="Sampling temperature")
    top_p: Optional[float] = Field(None, description="Nucleus sampling parameter")
    n: Optional[int] = Field(1, description="Number of completions to generate")
    stream: Optional[bool] = Field(False, description="Whether to stream the response")
    stop: Optional[Union[str, List[str]]] = Field(None, description="Stop sequences")
    presence_penalty: Optional[float] = Field(None, description="Presence penalty")
    frequency_penalty: Optional[float] = Field(None, description="Frequency penalty")
    logit_bias: Optional[Dict[str, float]] = Field(None, description="Logit bias")
    user: Optional[str] = Field(None, description="Unique identifier for the user")


class ChatCompletionChoice(BaseModel):
    """OpenAI compatible completion choice."""
    index: int = Field(..., description="Index of the choice")
    message: ChatMessage = Field(..., description="The message generated by the model")
    finish_reason: Optional[str] = Field(None, description="Reason the model stopped generating")


class ChatCompletionUsage(BaseModel):
    """OpenAI compatible token usage statistics."""
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt")
    completion_tokens: int = Field(..., description="Number of tokens in the completion")
    total_tokens: int = Field(..., description="Total number of tokens used")


class ChatCompletionResponse(BaseModel):
    """OpenAI compatible chat completion response."""
    id: str = Field(..., description="Unique identifier for the completion")
    object: str = Field("chat.completion", description="Object type")
    created: int = Field(..., description="Unix timestamp of creation")
    model: str = Field(..., description="Model used for completion")
    choices: List[ChatCompletionChoice] = Field(..., description="List of completion choices")
    usage: ChatCompletionUsage = Field(..., description="Token usage statistics")


class HealthResponse(BaseModel):
    """Health check response for Denis Unified V1."""
    status: str = Field(..., description="Health status")
    version: str = Field(..., description="Version identifier")
    timestamp: int = Field(..., description="Unix timestamp")
    components: Dict[str, Any] = Field(..., description="Component status information")


class ErrorResponse(BaseModel):
    """Error response model."""
    error: Dict[str, Any] = Field(..., description="Error details")
